apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: agent-db-credentials
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: agent-postgres-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_HOST: "simpledso-dev-agent-db.cgfgmecgq891.us-east-1.rds.amazonaws.com"
        DB_PORT: "5432"
        DB_NAME: "agent_core"
        DB_USER: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: "arn:aws:secretsmanager:us-east-1:104091534720:secret:rds!db-caf8965a-85eb-4c63-859d-16525b543228-cXeALb"
        property: username
    - secretKey: password
      remoteRef:
        key: "arn:aws:secretsmanager:us-east-1:104091534720:secret:rds!db-caf8965a-85eb-4c63-859d-16525b543228-cXeALb"
        property: password