apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: agent-db-credentials
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: agent-postgres-secret # Nombre del K8s Secret generado
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: simpledso-dev-agent-db-xxxx # Nombre/ARN del secreto en Secrets Manager
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: simpledso-dev-agent-db-xxxx
        property: port
    - secretKey: DB_USER
      remoteRef:
        key: simpledso-dev-agent-db-xxxx
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: simpledso-dev-agent-db-xxxx
        property: password
    - secretKey: DB_NAME
      remoteRef:
        key: simpledso-dev-agent-db-xxxx
        property: dbname