apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: agent-db-credentials
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: agent-postgres-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "simpledso/dev/agent-db/credentials" # Nombre estático que nunca cambia