name: simpledso-infra

on:
  workflow_dispatch:

concurrency:
  group: deploy-infra-dev
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./envs/dev/
    env:
      TF_BUCKET: "${{ vars.TF_BUCKET }}"
      TF_REGION: "${{ vars.TF_REGION }}"
      TF_DYNAMODB: "${{ vars.TF_DYNAMODB }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.5.0"
      - name: OIDC AWS Login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::104091534720:role/github-role-ecr
          aws-region: ${{env.TF_REGION}}
      - name: run terraform infra deployment
        run: |  
          terraform init \
          -backend-config="bucket=${TF_BUCKET}" \
          -backend-config="dynamodb_table=${TF_DYNAMODB}" \
          -backend-config="region=${TF_REGION}"
      - name: Terraform validate
        run: |
          terraform validate
      - name: Terraform plan
        run: |
          terraform plan -out=tfplan
      - name: Terraform apply
        run: |
          terraform apply -auto-approve tfplan