name: Destroy Bootstrap Backend

on:
  workflow_dispatch:
    inputs:
      confirm_destruction:
        description: 'Escribe "DESTROY" para confirmar la eliminación de la infra base'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  destroy_backend_s3:
    runs-on: ubuntu-latest
    environment: dev
    if: github.event.inputs.confirm_destruction == 'DESTROY'
    env:
      AWS_REGION: "${{vars.AWS_REGION}}"
      TF_ROLE: "${{ vars.AWS_ROLE_ARN }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get aws role OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{env.TF_ROLE}}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          required_version: "1.5.0"
      - name: Execute destroy terraform script
        run: |
          chmod 755 ./scripts/terraform/destroy_state_s3.sh
          ./scripts/terraform/destroy_state_s3.sh